#!/usr/bin/env python3
"""build_queue.py — turn unfollow decisions into unfollow_queue.js.

Reads either the analyser's candidates.csv (selecting rows whose `decision`
cell marks an unfollow) or a plain newline-delimited handle list, and writes
unfollow_queue.js defining `window.UNFOLLOW_TARGETS` for unfollow.js to load.

Strictly local: no network, standard library only. Python 3.9+.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys

DEFAULT_MARKERS = ("unfollow", "u", "yes", "y", "drop", "x")

# Instagram handles are letters, digits, periods and underscores.
_HANDLE_RE = re.compile(r"^[A-Za-z0-9._]+$")


def select_from_csv(rows, markers):
    """Yield usernames from candidates.csv rows whose decision is a marker."""
    marker_set = {m.strip().casefold() for m in markers}
    for row in rows:
        decision = (row.get("decision") or "").strip().casefold()
        username = (row.get("username") or "").strip()
        if username and decision in marker_set:
            yield username


def select_from_list(lines):
    """Yield handles from a newline-delimited list (skips blanks and # comments)."""
    for line in lines:
        handle = line.strip()
        if handle and not handle.startswith("#"):
            yield handle


def dedupe(handles):
    """De-duplicate case-insensitively, preserving first-seen order."""
    seen = set()
    result = []
    for handle in handles:
        key = handle.casefold()
        if key not in seen:
            seen.add(key)
            result.append(handle)
    return result


def render_queue_js(handles):
    """Render the unfollow_queue.js file content (handles JSON-escaped)."""
    return (
        "// Paste this FIRST. Loads the unfollow target list.\n"
        "// Generated by build_queue.py — do not edit by hand.\n"
        "window.UNFOLLOW_TARGETS = {};\n".format(json.dumps(handles))
    )


def _read_csv_rows(path):
    with open(path, "r", encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def _read_lines(path):
    with open(path, "r", encoding="utf-8") as fh:
        return fh.readlines()


def build_arg_parser():
    parser = argparse.ArgumentParser(
        description="Generate unfollow_queue.js from your unfollow decisions.",
    )
    source = parser.add_mutually_exclusive_group()
    source.add_argument(
        "--from-csv",
        metavar="PATH",
        help="candidates.csv with a filled `decision` column (default: candidates.csv).",
    )
    source.add_argument(
        "--from-list",
        metavar="PATH",
        help="Plain newline-delimited handle list (one username per line).",
    )
    parser.add_argument(
        "--out",
        default="unfollow_queue.js",
        help="Output path (default: unfollow_queue.js).",
    )
    parser.add_argument(
        "--markers",
        default=",".join(DEFAULT_MARKERS),
        help="Comma-separated decision values that mean 'unfollow' "
        "(default: {}).".format(",".join(DEFAULT_MARKERS)),
    )
    return parser


def main(argv=None):
    args = build_arg_parser().parse_args(argv)
    markers = [m for m in args.markers.split(",") if m.strip()]

    try:
        if args.from_list:
            handles = list(select_from_list(_read_lines(args.from_list)))
        else:
            csv_path = args.from_csv or "candidates.csv"
            handles = list(select_from_csv(_read_csv_rows(csv_path), markers))
    except OSError as exc:
        print("ERROR: cannot read input: {}".format(exc), file=sys.stderr)
        return 2

    handles = dedupe(handles)

    for handle in handles:
        if not _HANDLE_RE.match(handle):
            print("WARNING: unusual handle kept as-is: {!r}".format(handle), file=sys.stderr)

    if not handles:
        print(
            "ERROR: no unfollow targets selected — nothing written. "
            "Did you fill the `decision` column (e.g. 'unfollow')?",
            file=sys.stderr,
        )
        return 2

    try:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(render_queue_js(handles))
    except OSError as exc:
        print("ERROR: cannot write {}: {}".format(args.out, exc), file=sys.stderr)
        return 2

    print("Wrote {} ({} targets).".format(args.out, len(handles)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
